// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet.proto

package packet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_JSON  MessageType = 0
	MessageType_PROTO MessageType = 1
	MessageType_XML   MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "JSON",
	1: "PROTO",
	2: "XML",
}

var MessageType_value = map[string]int32{
	"JSON":  0,
	"PROTO": 1,
	"XML":   2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

type Request struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Ext                  *Ext     `protobuf:"bytes,2,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetExt() *Ext {
	if m != nil {
		return m.Ext
	}
	return nil
}

type Response struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Errno                int32    `protobuf:"varint,3,opt,name=errno,proto3" json:"errno,omitempty"`
	Body                 []byte   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Ext                  *Ext     `protobuf:"bytes,2,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetErrno() int32 {
	if m != nil {
		return m.Errno
	}
	return 0
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetExt() *Ext {
	if m != nil {
		return m.Ext
	}
	return nil
}

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{2}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type Header struct {
	Ver                  int32       `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	AppId                int32       `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Type                 MessageType `protobuf:"varint,3,opt,name=type,proto3,enum=packet.MessageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{3}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Header) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *Header) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_JSON
}

type Ext struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId               string   `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ext) Reset()         { *m = Ext{} }
func (m *Ext) String() string { return proto.CompactTextString(m) }
func (*Ext) ProtoMessage()    {}
func (*Ext) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{4}
}

func (m *Ext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ext.Unmarshal(m, b)
}
func (m *Ext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ext.Marshal(b, m, deterministic)
}
func (m *Ext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ext.Merge(m, src)
}
func (m *Ext) XXX_Size() int {
	return xxx_messageInfo_Ext.Size(m)
}
func (m *Ext) XXX_DiscardUnknown() {
	xxx_messageInfo_Ext.DiscardUnknown(m)
}

var xxx_messageInfo_Ext proto.InternalMessageInfo

func (m *Ext) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Ext) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

func init() {
	proto.RegisterEnum("packet.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Request)(nil), "packet.request")
	proto.RegisterType((*Response)(nil), "packet.response")
	proto.RegisterType((*Null)(nil), "packet.null")
	proto.RegisterType((*Header)(nil), "packet.header")
	proto.RegisterType((*Ext)(nil), "packet.ext")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor_e9ef1a6541f9f9e7) }

var fileDescriptor_e9ef1a6541f9f9e7 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xbf, 0xa5, 0xbf, 0x60, 0x20, 0xa4, 0x99, 0xf0, 0x8d, 0x78, 0x30, 0x21, 0x3d, 0x28,
	0x1a, 0x43, 0x13, 0x3c, 0x79, 0xf5, 0x86, 0x51, 0x31, 0xab, 0x07, 0xa3, 0x07, 0xb2, 0xb4, 0x93,
	0x42, 0x6c, 0xbb, 0xeb, 0x76, 0x21, 0x10, 0xff, 0x79, 0xd3, 0x2d, 0x35, 0x1e, 0xb9, 0xcd, 0x9b,
	0xd9, 0xf7, 0x3e, 0x2f, 0x59, 0xe8, 0x49, 0x1e, 0x7f, 0x92, 0x9e, 0x48, 0x25, 0xb4, 0x40, 0xaf,
	0x56, 0x61, 0x02, 0xbe, 0xa2, 0xaf, 0x0d, 0x95, 0x1a, 0xcf, 0xc1, 0x5b, 0x11, 0x4f, 0x48, 0x0d,
	0xad, 0x91, 0x35, 0xee, 0x4e, 0xfb, 0x93, 0x83, 0xa3, 0xde, 0xb2, 0xc3, 0x15, 0x11, 0x9c, 0xa5,
	0x48, 0xf6, 0x43, 0x7b, 0x64, 0x8d, 0x7b, 0xcc, 0xcc, 0x78, 0x06, 0x36, 0xed, 0xf4, 0xb0, 0x65,
	0x8c, 0xdd, 0xc6, 0x48, 0x3b, 0xcd, 0xaa, 0x7d, 0xf8, 0x0d, 0x6d, 0x45, 0xa5, 0x14, 0x45, 0x49,
	0x47, 0x63, 0x06, 0xe0, 0x92, 0x52, 0x85, 0x30, 0x1c, 0x97, 0xd5, 0xe2, 0x17, 0xee, 0x1c, 0x0f,
	0xf7, 0xc0, 0x29, 0x36, 0x59, 0x16, 0x7e, 0x34, 0x60, 0x0c, 0xc0, 0xde, 0x1e, 0xf8, 0x2e, 0xab,
	0x46, 0xfc, 0x0f, 0x1e, 0x97, 0x72, 0xb1, 0x4e, 0x4c, 0x8a, 0xcb, 0x5c, 0x2e, 0xe5, 0x2c, 0xc1,
	0x31, 0x38, 0x7a, 0x2f, 0xc9, 0x54, 0xe8, 0x4f, 0x07, 0x4d, 0x74, 0x4e, 0x65, 0xc9, 0x53, 0x5a,
	0x54, 0x37, 0x66, 0x5e, 0x84, 0xb7, 0xa6, 0x03, 0x9e, 0x42, 0x5b, 0x2b, 0x1e, 0x53, 0x95, 0x54,
	0xc5, 0x77, 0x98, 0x6f, 0xf4, 0x2c, 0xc1, 0x13, 0xf0, 0x4b, 0xc9, 0x8b, 0x86, 0xd1, 0x61, 0x5e,
	0x25, 0x67, 0xc9, 0xd5, 0x35, 0xf4, 0xfe, 0x06, 0x62, 0x1b, 0x9c, 0xfb, 0x97, 0xf9, 0x53, 0xf0,
	0x0f, 0x3b, 0xe0, 0x3e, 0xb3, 0xf9, 0xeb, 0x3c, 0xb0, 0xd0, 0x07, 0xfb, 0xed, 0xf1, 0x21, 0x68,
	0xdd, 0x5d, 0xbe, 0x5f, 0xa4, 0x6b, 0xbd, 0xda, 0x2c, 0x27, 0xb1, 0xc8, 0xa3, 0x15, 0xcf, 0xd6,
	0x5b, 0xa1, 0xa2, 0x58, 0xe4, 0xb9, 0x28, 0xa2, 0x54, 0x64, 0xbc, 0x48, 0xa3, 0xba, 0xe6, 0xd2,
	0x33, 0x5f, 0x7d, 0xf3, 0x13, 0x00, 0x00, 0xff, 0xff, 0x50, 0xd2, 0xf0, 0x9a, 0xfa, 0x01, 0x00,
	0x00,
}
